import {Geist, Geist_Mono} from "next/font/google";
import styles from "@/styles/Home.module.css";
import {HeadMeta} from "@/components/HeadMeta/HeadMeta";
import {getLayout} from "@/components/Layout/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function Home() {
  return (
    <>
      <HeadMeta title={'Create Next App'} description={'Generated by create next app'} />
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
         <h1>Rick and Morty</h1>
      </div>
    </>
  );
}

Home.getLayout = getLayout
export default Home